In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
df = pd.read_csv('../data/Telco_customer_churn.csv')
df

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

Data Inspection, Cleaning and Tranformation

In [ ]:
# Dataframe basic information
df.info()

0                True
1                True
2                True
3                True
4                True
                ...
7039             True
7040             True
7041             True
7042             True
TotalCharges    False
Name: Country, Length: 7044, dtype: bool

In [21]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [24]:
print('Dataframe Shape:')
print(df.shape)
print('')
print('Dataframe tail and head:')
print(df.head(10))
print(df.tail(5))
print('')
print('Dataframe info')
print(df.info())
print('')
print('Datafram types')
print(df.dtypes)
print('')
print(df.columns.tolist())

Dataframe Shape:
(7044, 33)

Dataframe tail and head:
   CustomerID  Count        Country       State         City  Zip Code  \
0  3668-QPYBK    1.0  United States  California  Los Angeles   90003.0
1  9237-HQITU    1.0  United States  California  Los Angeles   90005.0
2  9305-CDSKC    1.0  United States  California  Los Angeles   90006.0
3  7892-POOKP    1.0  United States  California  Los Angeles   90010.0
4  0280-XJGEX    1.0  United States  California  Los Angeles   90015.0
5  4190-MFLUW    1.0  United States  California  Los Angeles   90020.0
6  8779-QRDMV    1.0  United States  California  Los Angeles   90022.0
7  1066-JKSGK    1.0  United States  California  Los Angeles   90024.0
8  6467-CHFZW    1.0  United States  California  Los Angeles   90028.0
9  8665-UTDHZ    1.0  United States  California  Los Angeles   90029.0

                 Lat Long   Latitude   Longitude  Gender  ...        Contract  \
0  33.964131, -118.272783  33.964131 -118.272783    Male  ...  Month-to-month
1   34.059281, -118.30742  34.059281 -118.307420  Female  ...  Month-to-month
2  34.048013, -118.293953  34.048013 -118.293953  Female  ...  Month-to-month
3  34.062125, -118.315709  34.062125 -118.315709  Female  ...  Month-to-month
4  34.039224, -118.266293  34.039224 -118.266293    Male  ...  Month-to-month
5  34.066367, -118.309868  34.066367 -118.309868  Female  ...  Month-to-month
6   34.02381, -118.156582  34.023810 -118.156582    Male  ...  Month-to-month
7  34.066303, -118.435479  34.066303 -118.435479    Male  ...  Month-to-month
8  34.099869, -118.326843  34.099869 -118.326843    Male  ...  Month-to-month
9  34.089953, -118.294824  34.089953 -118.294824    Male  ...  Month-to-month

  Paperless Billing             Payment Method  Monthly Charges Total Charges  \
0               Yes               Mailed check            53.85        108.15
1               Yes           Electronic check            70.70        151.65
2               Yes           Electronic check            99.65         820.5
3               Yes           Electronic check           104.80       3046.05
4               Yes  Bank transfer (automatic)           103.70        5036.3
5                No    Credit card (automatic)            55.20        528.35
6               Yes           Electronic check            39.65         39.65
7                No               Mailed check            20.15         20.15
8               Yes           Electronic check            99.35       4749.15
9                No           Electronic check            30.20          30.2

  Churn Label Churn Value Churn Score    CLTV  \
0         Yes         1.0        86.0  3239.0
1         Yes         1.0        67.0  2701.0
2         Yes         1.0        86.0  5372.0
3         Yes         1.0        84.0  5003.0
4         Yes         1.0        89.0  5340.0
5         Yes         1.0        78.0  5925.0
6         Yes         1.0       100.0  5433.0
7         Yes         1.0        92.0  4832.0
8         Yes         1.0        77.0  5789.0
9         Yes         1.0        97.0  2915.0

                                Churn Reason
0               Competitor made better offer
1                                      Moved
2                                      Moved
3                                      Moved
4              Competitor had better devices
5  Competitor offered higher download speeds
6               Competitor offered more data
7               Competitor made better offer
8              Competitor had better devices
9              Competitor had better devices

[10 rows x 33 columns]
              CustomerID  Count        Country       State          City  \
7039          6840-RESVB    1.0  United States  California      Adelanto
7040          2234-XADUH    1.0  United States  California         Amboy
7041          4801-JZAZL    1.0  United States  California  Angelus Oaks
7042          3186-AJIEK    1.0  United States  California  Apple Valley
TotalCharges         NaN    NaN            NaN         NaN           NaN

              Zip Code                Lat Long   Latitude   Longitude  Gender  \
7039           92301.0  34.667815, -117.536183  34.667815 -117.536183    Male
7040           92304.0  34.559882, -115.637164  34.559882 -115.637164  Female
7041           92305.0     34.1678, -116.86433  34.167800 -116.864330  Female
7042           92308.0  34.424926, -117.184503  34.424926 -117.184503    Male
TotalCharges       NaN                     NaN        NaN         NaN     NaN

              ...        Contract Paperless Billing  \
7039          ...        One year               Yes
7040          ...        One year               Yes
7041          ...  Month-to-month               Yes
7042          ...        Two year               Yes
TotalCharges  ...             NaN               NaN

                         Payment Method  Monthly Charges Total Charges  \
7039                       Mailed check            84.80        1990.5
7040            Credit card (automatic)           103.20        7362.9
7041                   Electronic check            29.60        346.45
7042          Bank transfer (automatic)           105.65        6844.5
TotalCharges                        NaN              NaN           NaN

             Churn Label Churn Value Churn Score    CLTV Churn Reason
7039                  No         0.0        59.0  2140.0          NaN
7040                  No         0.0        71.0  5560.0          NaN
7041                  No         0.0        59.0  2793.0          NaN
7042                  No         0.0        38.0  5097.0          NaN
TotalCharges         NaN         NaN         NaN     NaN          NaN

[5 rows x 33 columns]

Dataframe info
<class 'pandas.DataFrame'>
Index: 7044 entries, 0 to TotalCharges
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   float64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   float64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   float64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   float64
 30  Churn Score        7043 non-null   float64
 31  CLTV               7043 non-null   float64
 32  Churn Reason       1869 non-null   object
dtypes: float64(9), object(24)
memory usage: 2.1+ MB
None

Datafram types
CustomerID            object
Count                float64
Country               object
State                 object
City                  object
Zip Code             float64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months        float64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges         object
Churn Label           object
Churn Value          float64
Churn Score          float64
CLTV                 float64
Churn Reason          object
dtype: object

['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason']

Data Quality Assessment

In [48]:
# Missing Values
print(df.isnull().sum())

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [49]:
print(df.isnull().mean() * 100)

CustomerID            0.000000
Count                 0.000000
Country               0.000000
State                 0.000000
City                  0.000000
Zip Code              0.000000
Lat Long              0.000000
Latitude              0.000000
Longitude             0.000000
Gender                0.000000
Senior Citizen        0.000000
Partner               0.000000
Dependents            0.000000
Tenure Months         0.000000
Phone Service         0.000000
Multiple Lines        0.000000
Internet Service      0.000000
Online Security       0.000000
Online Backup         0.000000
Device Protection     0.000000
Tech Support          0.000000
Streaming TV          0.000000
Streaming Movies      0.000000
Contract              0.000000
Paperless Billing     0.000000
Payment Method        0.000000
Monthly Charges       0.000000
Total Charges         0.000000
Churn Label           0.000000
Churn Value           0.000000
Churn Score           0.000000
CLTV                  0.000000
Churn Reason         73.463013
dtype: float64

In [ ]:
# Duplicated Values
print(df.duplicated().sum())

0